"""Add school_id to audit_logs

Revision ID: 88aec839a977
Revises: 891e8ce6fc45
Create Date: 2026-03-21 06:54:00.471086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88aec839a977'
down_revision: Union[str, None] = '891e8ce6fc45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('school_id', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'school_id')
    # ### end Alembic commands ###
