"""Add academics and faculty tables

Revision ID: 891e8ce6fc45
Revises: 25d20cecb525
Create Date: 2026-03-20 09:15:52.084074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891e8ce6fc45'
down_revision: Union[str, None] = '25d20cecb525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
