"use client";

import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { Sparkles, RefreshCw, AlertTriangle, ShieldAlert, Lightbulb, Activity } from "lucide-react";

interface Insight {
  title: string;
  description: string;
  severity: "CRITICAL" | "WARNING" | "RECOMMENDATION";
  category: string;
  suggested_action: string;
  impact: string;
}

type TelemetryStats = {
  active_agents: number;
  automations_today: number;
  active_projects: number;
  system_health: number;
  throughput: number;
};

export default function AIInsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [stats, setStats] = useState<TelemetryStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState("");

  useEffect(() => {
    void loadInsights();
  }, []);

  const loadInsights = async () => {
    setLoading(true);
    setError("");
    try {
      const [insightData, telemetryData] = await Promise.all([
        api<Insight[]>("/api/ai/insights"),
        api<TelemetryStats>("/api/telemetry/stats"),
      ]);
      setInsights(insightData ?? []);
      setStats(telemetryData ?? null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to load insights.");
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError("");
    try {
      await api("/api/ai/insights/generate", { method: "POST" });
      await loadInsights();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to generate insights.");
    } finally {
      setGenerating(false);
    }
  };

  const getSeverityStyle = (severity: string) => {
    switch (severity) {
      case "CRITICAL": return "bg-red-50 dark:bg-red-900/10 border-red-200 dark:border-red-900/50 text-red-800 dark:text-red-300";
      case "WARNING": return "bg-amber-50 dark:bg-amber-900/10 border-amber-200 dark:border-amber-900/50 text-amber-800 dark:text-amber-300";
      case "RECOMMENDATION": return "bg-blue-50 dark:bg-blue-900/10 border-blue-200 dark:border-blue-900/50 text-blue-800 dark:text-blue-300";
      default: return "bg-slate-50 dark:bg-slate-900/50 border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-300";
    }
  };

  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case "CRITICAL": return <ShieldAlert className="w-8 h-8 text-red-500" />;
      case "WARNING": return <AlertTriangle className="w-8 h-8 text-amber-500" />;
      case "RECOMMENDATION": return <Lightbulb className="w-8 h-8 text-blue-500" />;
      default: return <Activity className="w-8 h-8 text-slate-500" />;
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] gap-4">
        <RefreshCw className="w-8 h-8 text-purple-500 animate-spin" />
        <p className="text-slate-500 dark:text-slate-400 font-medium animate-pulse">Running diagnostic models...</p>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8 p-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight">AI Insights & Telemetry</h1>
          <p className="text-slate-500 dark:text-slate-400 mt-2 text-lg">Proactive analysis and platform recommendations generated by Groq</p>
        </div>
        <button 
          onClick={handleGenerate} 
          disabled={generating}
          className="flex items-center gap-2 px-6 py-3 bg-purple-600 text-white rounded-xl hover:bg-purple-700 transition-colors font-bold disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-purple-500/20"
        >
          {generating ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
          {generating ? "Analyzing Data..." : "Regenerate Insights"}
        </button>
      </div>

      {error ? <div className="px-4 py-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-sm">{error}</div> : null}

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6 flex flex-col justify-center">
           <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Active Agents</span>
          <span className="text-3xl font-black text-slate-900 dark:text-white">{stats?.active_agents ?? "-"}</span>
        </div>
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6 flex flex-col justify-center">
           <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Avg Latency</span>
          <span className="text-3xl font-black text-emerald-500">245ms</span>
        </div>
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6 flex flex-col justify-center">
           <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Success Rate</span>
          <span className="text-3xl font-black text-emerald-500">{stats ? `${stats.system_health}%` : "-"}</span>
        </div>
        <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6 flex flex-col justify-center">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Automations Today</span>
          <span className="text-3xl font-black text-red-500">{stats?.automations_today ?? "-"}</span>
        </div>
      </div>

      <div className="grid gap-6">
        {insights.map((insight, index) => (
          <div key={index} className={`rounded-3xl border-2 p-8 transition-transform hover:-translate-y-1 ${getSeverityStyle(insight.severity)}`}>
            <div className="flex items-start gap-6">
              <div className="shrink-0 p-3 bg-white/50 dark:bg-slate-900/50 rounded-2xl shadow-sm">
                {getSeverityIcon(insight.severity)}
              </div>
              <div className="flex-1">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-xl font-bold">{insight.title}</h3>
                  <span className="px-3 py-1 text-[10px] font-black tracking-widest uppercase rounded-lg bg-white/60 dark:bg-slate-900/60 shadow-sm">
                    {insight.category}
                  </span>
                </div>
                <p className="opacity-90 text-lg mb-6 leading-relaxed">{insight.description}</p>
                <div className="grid grid-cols-2 gap-4">
                  <div className="bg-white/60 dark:bg-slate-900/40 rounded-xl p-4">
                    <p className="text-[10px] font-black opacity-60 uppercase tracking-widest mb-2">Suggested Action</p>
                    <p className="font-medium text-sm">{insight.suggested_action}</p>
                  </div>
                  <div className="bg-white/60 dark:bg-slate-900/40 rounded-xl p-4">
                    <p className="text-[10px] font-black opacity-60 uppercase tracking-widest mb-2">Impact</p>
                    <p className="font-medium text-sm">{insight.impact}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}