from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.academics import (
    AcademicCalendarEvent,
    AcademicsAutomationRun,
    CalendarEventType,
    Course,
    CurriculumAuditEntry,
    CurriculumAuditStatus,
    ExamSchedule,
    ExamScheduleStatus,
    Faculty,
    SubstitutionLog,
    SubstitutionStatus,
    TimetableSlot,
    TimetableSlotStatus,
)


WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
SLOT_WINDOWS = [(9, 0, 10, 30), (10, 45, 12, 15), (13, 30, 15, 0), (15, 15, 16, 45)]
DEFAULT_HALLS = [
    {"name": "Hall A", "capacity": 120},
    {"name": "Hall B", "capacity": 90},
    {"name": "Lab 1", "capacity": 60},
]


class AcademicsOpsService:
    def parse_context(self, raw: str | None) -> dict[str, Any]:
        if not raw:
            return {}

        text = raw.strip()
        if text.startswith("```"):
            text = text.strip("`")
            if "\n" in text:
                text = text.split("\n", 1)[1]

        if text.startswith("{"):
            try:
                loaded = json.loads(text)
                if isinstance(loaded, dict):
                    return loaded
            except Exception:
                pass

        parsed: dict[str, Any] = {}
        for line in text.splitlines():
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            parsed[key.strip().lower().replace(" ", "_")] = value.strip()
        return parsed

    def _as_int(self, value: Any, default: int) -> int:
        try:
            parsed = int(str(value).strip())
            return parsed if parsed > 0 else default
        except Exception:
            return default

    def _as_float(self, value: Any, default: float) -> float:
        try:
            return float(str(value).strip())
        except Exception:
            return default

    def _as_list(self, value: Any) -> list[Any]:
        if isinstance(value, list):
            return value
        if isinstance(value, str) and value.strip():
            if value.strip().startswith("["):
                try:
                    loaded = json.loads(value)
                    if isinstance(loaded, list):
                        return loaded
                except Exception:
                    pass
            return [part.strip() for part in value.split(",") if part.strip()]
        return []

    def _school(self, context: dict[str, Any]) -> str:
        school = str(context.get("school_id") or context.get("school") or "atlas").strip().lower()
        return school or "atlas"

    def _start_of_next_week(self) -> datetime:
        now = datetime.now(timezone.utc)
        days_until_monday = (7 - now.weekday()) % 7
        base = now + timedelta(days=days_until_monday)
        return base.replace(hour=0, minute=0, second=0, microsecond=0)

    def _stable_percent(self, seed: str, floor: int = 55, ceiling: int = 95) -> float:
        score = sum(ord(ch) for ch in seed) % max(1, (ceiling - floor + 1))
        return float(floor + score)

    async def ensure_timetable_seed(self, db: AsyncSession, school_id: str) -> None:
        existing = await db.scalar(
            select(func.count()).select_from(TimetableSlot).where(TimetableSlot.school_id == school_id)
        )
        if int(existing or 0) > 0:
            return

        rows = await db.execute(
            select(Course, Faculty)
            .join(Faculty, Faculty.id == Course.faculty_id, isouter=True)
            .where(Course.school_id == school_id)
            .limit(24)
        )
        pairs = rows.all()

        if not pairs:
            faculty_rows = await db.execute(select(Faculty).where(Faculty.school_id == school_id).limit(8))
            faculty_list = faculty_rows.scalars().all()
            pairs = []
            for idx, faculty in enumerate(faculty_list, start=1):
                fake_course = Course(
                    code=f"{school_id.upper()}-{200 + idx}",
                    name=f"Core Module {idx}",
                    semester=(idx % 8) + 1,
                    faculty_id=faculty.id,
                    school_id=school_id,
                    syllabus_summary="Autogenerated module for timetable bootstrap.",
                )
                db.add(fake_course)
                await db.flush()
                pairs.append((fake_course, faculty))

        base = self._start_of_next_week()
        for idx, (course, faculty) in enumerate(pairs[:20]):
            day_index = idx % len(WEEKDAYS)
            slot_index = idx % len(SLOT_WINDOWS)
            sh, sm, eh, em = SLOT_WINDOWS[slot_index]
            day_anchor = base + timedelta(days=day_index)
            start_at = day_anchor.replace(hour=sh, minute=sm)
            end_at = day_anchor.replace(hour=eh, minute=em)

            db.add(
                TimetableSlot(
                    school_id=school_id,
                    programme=f"Semester {(course.semester if hasattr(course, 'semester') else ((idx % 8) + 1))}",
                    semester=f"Semester {(course.semester if hasattr(course, 'semester') else ((idx % 8) + 1))}",
                    section=chr(65 + (idx % 3)),
                    course_id=course.id,
                    course_name=course.name,
                    faculty_id=faculty.id if faculty else None,
                    faculty_name=faculty.name if faculty else "TBD Faculty",
                    room=f"R-{100 + (idx % 12)}",
                    day_of_week=WEEKDAYS[day_index],
                    start_time=start_at,
                    end_time=end_at,
                    status=TimetableSlotStatus.PUBLISHED,
                    metadata_json={"seeded": True},
                )
            )
        await db.flush()

    async def ensure_exam_seed(self, db: AsyncSession, school_id: str) -> None:
        existing = await db.scalar(
            select(func.count()).select_from(ExamSchedule).where(ExamSchedule.school_id == school_id)
        )
        if int(existing or 0) > 0:
            return

        course_rows = await db.execute(select(Course).where(Course.school_id == school_id).limit(12))
        courses = course_rows.scalars().all()
        if not courses:
            return

        base = self._start_of_next_week() + timedelta(days=14)
        for idx, course in enumerate(courses):
            hall = DEFAULT_HALLS[idx % len(DEFAULT_HALLS)]
            exam_day = base + timedelta(days=idx)
            start_at = exam_day.replace(hour=9, minute=0)
            end_at = exam_day.replace(hour=11, minute=0)
            registered = self._as_int(self._stable_percent(course.code, 45, 110), 60)
            db.add(
                ExamSchedule(
                    school_id=school_id,
                    exam_name=f"{course.name} - End Term",
                    course_id=course.id,
                    course_name=course.name,
                    programme=f"Semester {course.semester}",
                    section=chr(65 + (idx % 3)),
                    exam_date=exam_day,
                    start_time=start_at,
                    end_time=end_at,
                    hall_name=hall["name"],
                    hall_capacity=int(hall["capacity"]),
                    registered_students=registered,
                    proctor_name=None,
                    status=ExamScheduleStatus.PROPOSED,
                    metadata_json={"seeded": True},
                )
            )
        await db.flush()

    async def ensure_calendar_seed(self, db: AsyncSession, school_id: str) -> None:
        existing = await db.scalar(
            select(func.count()).select_from(AcademicCalendarEvent).where(AcademicCalendarEvent.school_id == school_id)
        )
        if int(existing or 0) > 0:
            return

        now = datetime.now(timezone.utc)
        sem_start = now.replace(month=7, day=1, hour=9, minute=0, second=0, microsecond=0)
        sem_end = sem_start + timedelta(days=140)
        events = [
            ("Semester Start", CalendarEventType.EVENT, sem_start, sem_start + timedelta(hours=2), False),
            ("Orientation Week", CalendarEventType.EVENT, sem_start + timedelta(days=1), sem_start + timedelta(days=5), False),
            ("Midterm Exams", CalendarEventType.EXAM, sem_start + timedelta(days=60), sem_start + timedelta(days=66), False),
            ("End Semester Exams", CalendarEventType.EXAM, sem_end - timedelta(days=14), sem_end - timedelta(days=2), False),
            ("Independence Day", CalendarEventType.HOLIDAY, sem_start.replace(month=8, day=15), sem_start.replace(month=8, day=15, hour=18), True),
        ]

        for title, event_type, start_at, end_at, is_holiday in events:
            db.add(
                AcademicCalendarEvent(
                    school_id=school_id,
                    title=title,
                    event_type=event_type,
                    start_at=start_at,
                    end_at=end_at,
                    owner="Academic Cell",
                    is_holiday=is_holiday,
                    is_locked=event_type in {CalendarEventType.EXAM, CalendarEventType.HOLIDAY},
                    metadata_json={"seeded": True},
                )
            )
        await db.flush()

    async def ensure_curriculum_seed(self, db: AsyncSession, school_id: str) -> None:
        existing = await db.scalar(
            select(func.count()).select_from(CurriculumAuditEntry).where(CurriculumAuditEntry.school_id == school_id)
        )
        if int(existing or 0) > 0:
            return

        rows = await db.execute(select(Course).where(Course.school_id == school_id).limit(20))
        courses = rows.scalars().all()
        for course in courses:
            exam_freq = self._stable_percent(course.code, 35, 95)
            syllabus_weight = self._stable_percent(f"{course.code}-syllabus", 35, 95)
            industry_rel = self._stable_percent(f"{course.code}-industry", 45, 98)
            diff = abs(exam_freq - syllabus_weight)
            alignment = max(40.0, min(98.0, round((industry_rel + (100.0 - diff)) / 2, 1)))
            status = CurriculumAuditStatus.ALIGNED if alignment >= 85 else (
                CurriculumAuditStatus.REVIEWING if alignment >= 70 else CurriculumAuditStatus.NEEDS_UPDATE
            )
            db.add(
                CurriculumAuditEntry(
                    school_id=school_id,
                    programme=f"Semester {course.semester}",
                    semester=f"Semester {course.semester}",
                    course_code=course.code,
                    course_name=course.name,
                    status=status,
                    alignment_score=alignment,
                    exam_frequency=exam_freq,
                    syllabus_weight=syllabus_weight,
                    industry_relevance=industry_rel,
                    gaps=[],
                    recommendations=[],
                )
            )
        await db.flush()

    async def parse_timetable_constraints(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        constraints = context.get("constraints")
        if not isinstance(constraints, list) or not constraints:
            text = str(context.get("constraint_text") or context.get("instructions") or "").strip()
            constraints = [line.strip() for line in text.split(";") if line.strip()] if text else []

        hard: list[dict[str, Any]] = []
        soft: list[dict[str, Any]] = []
        for item in constraints:
            raw = str(item).strip()
            if not raw:
                continue
            payload = {
                "constraint": raw,
                "weight": 100 if any(token in raw.lower() for token in ["must", "never", "no "]) else 40,
                "type": "hard" if any(token in raw.lower() for token in ["must", "never", "no "]) else "soft",
            }
            if payload["type"] == "hard":
                hard.append(payload)
            else:
                soft.append(payload)

        await self.ensure_timetable_seed(db, school_id)
        reflection = f"Parsed {len(hard)} hard and {len(soft)} soft timetable constraints for {school_id}."
        return reflection, [
            {"status": "constraints_ingested", "school_id": school_id, "input_count": len(constraints)},
            {"status": "constraints_structured", "hard_constraints": hard, "soft_constraints": soft},
        ]

    async def detect_timetable_conflicts(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_timetable_seed(db, school_id)

        rows = await db.execute(
            select(TimetableSlot)
            .where(TimetableSlot.school_id == school_id)
            .order_by(TimetableSlot.day_of_week, TimetableSlot.start_time)
        )
        slots = rows.scalars().all()

        faculty_map: dict[tuple[str, datetime, datetime, str], list[TimetableSlot]] = defaultdict(list)
        room_map: dict[tuple[str, datetime, datetime, str], list[TimetableSlot]] = defaultdict(list)
        section_map: dict[tuple[str, datetime, datetime, str], list[TimetableSlot]] = defaultdict(list)

        for slot in slots:
            faculty_map[(slot.day_of_week, slot.start_time, slot.end_time, slot.faculty_name)].append(slot)
            room_map[(slot.day_of_week, slot.start_time, slot.end_time, slot.room)].append(slot)
            section_map[(slot.day_of_week, slot.start_time, slot.end_time, slot.section)].append(slot)

        hard_conflicts: list[dict[str, Any]] = []
        for key_map, conflict_type in (
            (faculty_map, "faculty_double_booking"),
            (room_map, "room_double_booking"),
            (section_map, "section_overlap"),
        ):
            for key, grouped in key_map.items():
                if len(grouped) <= 1:
                    continue
                hard_conflicts.append(
                    {
                        "conflict_type": conflict_type,
                        "day": key[0],
                        "start_time": key[1].isoformat(),
                        "end_time": key[2].isoformat(),
                        "entity": key[3],
                        "affected_slots": [slot.id for slot in grouped],
                        "severity": "critical",
                        "suggested_resolution": "Reassign one slot to alternate room/faculty/section window.",
                    }
                )

        soft_conflicts: list[dict[str, Any]] = []
        faculty_day_slots: dict[tuple[str, str], list[TimetableSlot]] = defaultdict(list)
        for slot in slots:
            faculty_day_slots[(slot.faculty_name, slot.day_of_week)].append(slot)

        for (faculty_name, day), grouped in faculty_day_slots.items():
            sorted_slots = sorted(grouped, key=lambda x: x.start_time)
            if len(sorted_slots) >= 4:
                soft_conflicts.append(
                    {
                        "conflict_type": "high_consecutive_load",
                        "faculty": faculty_name,
                        "day": day,
                        "slots": [slot.id for slot in sorted_slots],
                        "severity": "warning",
                        "suggested_resolution": "Insert a break window or move one class to another day.",
                    }
                )

        reflection = (
            f"Conflict scan complete for {school_id}: "
            f"{len(hard_conflicts)} hard conflicts and {len(soft_conflicts)} soft risks."
        )
        return reflection, [
            {"status": "timetable_loaded", "slot_count": len(slots), "school_id": school_id},
            {
                "status": "conflict_report_generated",
                "hard_conflicts": hard_conflicts,
                "soft_conflicts": soft_conflicts,
                "hard_conflict_count": len(hard_conflicts),
                "soft_conflict_count": len(soft_conflicts),
            },
        ]

    async def manage_substitutions(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_timetable_seed(db, school_id)

        absent_faculty = str(
            context.get("absent_faculty")
            or context.get("faculty")
            or context.get("absent_faculty_name")
            or ""
        ).strip()
        reason = str(context.get("reason") or "Faculty unavailable").strip()
        day = str(context.get("day") or context.get("day_of_week") or "").strip().title()

        slot_rows = await db.execute(select(TimetableSlot).where(TimetableSlot.school_id == school_id))
        all_slots = slot_rows.scalars().all()

        impacted = [
            slot for slot in all_slots
            if (not absent_faculty or slot.faculty_name.lower() == absent_faculty.lower()) and (not day or slot.day_of_week == day)
        ]
        if not impacted:
            impacted = all_slots[:2]

        faculty_rows = await db.execute(select(Faculty).where(Faculty.school_id == school_id))
        faculty_pool = faculty_rows.scalars().all()

        recommendations: list[dict[str, Any]] = []
        for slot in impacted:
            ranked: list[dict[str, Any]] = []
            for faculty in faculty_pool:
                if slot.faculty_id and faculty.id == slot.faculty_id:
                    continue
                busy = any(
                    other.faculty_id == faculty.id
                    and other.day_of_week == slot.day_of_week
                    and other.start_time == slot.start_time
                    and other.end_time == slot.end_time
                    for other in all_slots
                )
                if busy:
                    continue

                load = sum(1 for other in all_slots if other.faculty_id == faculty.id and other.day_of_week == slot.day_of_week)
                subject_fit = 1 if faculty.department.lower().split(" ")[0] in slot.course_name.lower() else 0
                score = max(30.0, min(99.0, 88.0 + (subject_fit * 8.0) - (load * 4.5)))
                ranked.append(
                    {
                        "faculty_id": faculty.id,
                        "faculty_name": faculty.name,
                        "department": faculty.department,
                        "current_day_load": load,
                        "score": round(score, 1),
                    }
                )

            ranked.sort(key=lambda x: float(x["score"]), reverse=True)
            best = ranked[0] if ranked else None

            log = SubstitutionLog(
                school_id=school_id,
                timetable_slot_id=slot.id,
                absent_faculty_id=slot.faculty_id,
                absent_faculty_name=slot.faculty_name,
                substitute_faculty_id=int(best["faculty_id"]) if best else None,
                substitute_faculty_name=str(best["faculty_name"]) if best else "No candidate",
                course_name=slot.course_name,
                section=slot.section,
                slot_date=slot.start_time,
                start_time=slot.start_time,
                end_time=slot.end_time,
                reason=reason,
                status=SubstitutionStatus.RECOMMENDED,
                recommendation_score=float(best["score"]) if best else 0.0,
                notification_payload={"ranked_candidates": ranked[:5]},
            )
            db.add(log)

            recommendations.append(
                {
                    "slot_id": slot.id,
                    "course_name": slot.course_name,
                    "section": slot.section,
                    "day": slot.day_of_week,
                    "time": f"{slot.start_time.strftime('%H:%M')} - {slot.end_time.strftime('%H:%M')}",
                    "recommended_substitute": best,
                    "top_candidates": ranked[:3],
                }
            )

        await db.flush()
        reflection = f"Prepared substitution recommendations for {len(recommendations)} impacted classes in {school_id}."
        return reflection, [
            {
                "status": "absence_impact_mapped",
                "absent_faculty": absent_faculty or "auto-selected",
                "impacted_class_count": len(recommendations),
            },
            {
                "status": "substitute_ranking_completed",
                "recommendations": recommendations,
            },
        ]

    async def notify_substitutions(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        limit = self._as_int(context.get("limit") or 8, 8)

        rows = await db.execute(
            select(SubstitutionLog)
            .where(
                SubstitutionLog.school_id == school_id,
                SubstitutionLog.status.in_([SubstitutionStatus.RECOMMENDED, SubstitutionStatus.NOTIFIED]),
            )
            .order_by(SubstitutionLog.created_at.desc())
            .limit(limit)
        )
        logs = rows.scalars().all()

        notices: list[dict[str, Any]] = []
        for log in logs:
            hod = (
                f"HOD Notice: {log.absent_faculty_name} unavailable for {log.course_name} "
                f"({log.section}) at {log.start_time.strftime('%H:%M')}. "
                f"Recommended substitute: {log.substitute_faculty_name}."
            )
            faculty_msg = (
                f"Faculty Notice: You are proposed as substitute for {log.course_name} "
                f"({log.section}) on {log.slot_date.strftime('%Y-%m-%d')} {log.start_time.strftime('%H:%M')}."
            )
            class_msg = (
                f"Class Update: {log.course_name} ({log.section}) will be handled by "
                f"{log.substitute_faculty_name}. Venue/time unchanged unless informed."
            )
            payload = {
                "hod_notice": hod,
                "faculty_notice": faculty_msg,
                "class_notice": class_msg,
            }
            existing = log.notification_payload if isinstance(log.notification_payload, dict) else {}
            existing.update(payload)
            log.notification_payload = existing
            log.status = SubstitutionStatus.NOTIFIED
            notices.append({"substitution_id": log.id, **payload})

        await db.flush()
        reflection = f"Generated communication packs for {len(notices)} substitution records in {school_id}."
        return reflection, [
            {"status": "substitution_logs_loaded", "records": len(logs)},
            {"status": "notification_pack_generated", "notifications": notices},
        ]

    async def apply_substitution_updates(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        limit = self._as_int(context.get("limit") or 6, 6)

        rows = await db.execute(
            select(SubstitutionLog)
            .where(
                SubstitutionLog.school_id == school_id,
                SubstitutionLog.status.in_([SubstitutionStatus.RECOMMENDED, SubstitutionStatus.NOTIFIED]),
            )
            .order_by(SubstitutionLog.created_at.desc())
            .limit(limit)
        )
        logs = rows.scalars().all()

        patches: list[dict[str, Any]] = []
        for log in logs:
            if not log.timetable_slot_id:
                continue
            slot = await db.scalar(select(TimetableSlot).where(TimetableSlot.id == log.timetable_slot_id))
            if not slot:
                continue

            slot.faculty_id = log.substitute_faculty_id
            slot.faculty_name = log.substitute_faculty_name
            slot.status = TimetableSlotStatus.SUBSTITUTED
            metadata = slot.metadata_json if isinstance(slot.metadata_json, dict) else {}
            metadata.update(
                {
                    "substitution_id": log.id,
                    "absent_faculty": log.absent_faculty_name,
                    "reason": log.reason,
                }
            )
            slot.metadata_json = metadata

            log.status = SubstitutionStatus.CONFIRMED
            log.confirmed_at = datetime.now(timezone.utc)
            patches.append(
                {
                    "slot_id": slot.id,
                    "course_name": slot.course_name,
                    "section": slot.section,
                    "old_faculty": log.absent_faculty_name,
                    "new_faculty": log.substitute_faculty_name,
                    "status": "confirmed",
                }
            )

        await db.flush()
        reflection = f"Applied {len(patches)} substitution patches to timetable for {school_id}."
        return reflection, [
            {"status": "substitution_candidates_loaded", "records": len(logs)},
            {"status": "timetable_patch_applied", "patches": patches},
        ]

    async def schedule_exams(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_exam_seed(db, school_id)

        cycle = str(context.get("exam_cycle") or context.get("exam_type") or "End Semester").strip()
        halls_raw = self._as_list(context.get("halls"))
        halls = []
        for item in halls_raw:
            if isinstance(item, dict) and item.get("name"):
                halls.append(
                    {
                        "name": str(item.get("name")),
                        "capacity": self._as_int(item.get("capacity"), 60),
                    }
                )
        if not halls:
            halls = DEFAULT_HALLS

        course_rows = await db.execute(select(Course).where(Course.school_id == school_id).limit(14))
        courses = course_rows.scalars().all()
        base = self._start_of_next_week() + timedelta(days=20)
        created: list[dict[str, Any]] = []

        for idx, course in enumerate(courses):
            hall = halls[idx % len(halls)]
            exam_day = base + timedelta(days=idx)
            start_at = exam_day.replace(hour=9 + (idx % 2) * 3, minute=0)
            end_at = start_at + timedelta(hours=2)
            registered = self._as_int(self._stable_percent(f"{course.code}-registered", 50, 130), 70)

            exam = ExamSchedule(
                school_id=school_id,
                exam_name=f"{course.name} - {cycle}",
                course_id=course.id,
                course_name=course.name,
                programme=f"Semester {course.semester}",
                section=chr(65 + (idx % 3)),
                exam_date=exam_day,
                start_time=start_at,
                end_time=end_at,
                hall_name=hall["name"],
                hall_capacity=int(hall["capacity"]),
                registered_students=registered,
                proctor_name=None,
                status=ExamScheduleStatus.PROPOSED,
                metadata_json={"cycle": cycle, "generated": True},
            )
            db.add(exam)
            await db.flush()
            created.append(
                {
                    "exam_id": exam.id,
                    "exam_name": exam.exam_name,
                    "date": exam.exam_date.date().isoformat(),
                    "time": f"{exam.start_time.strftime('%H:%M')} - {exam.end_time.strftime('%H:%M')}",
                    "hall": exam.hall_name,
                    "capacity_ok": exam.hall_capacity >= exam.registered_students,
                }
            )

        reflection = f"Generated {len(created)} proposed exam slots for {school_id} ({cycle})."
        return reflection, [
            {"status": "exam_inputs_resolved", "school_id": school_id, "cycle": cycle, "halls": halls},
            {"status": "exam_schedule_generated", "created_schedules": created[:20]},
        ]

    async def check_exam_clashes(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_exam_seed(db, school_id)

        rows = await db.execute(
            select(ExamSchedule).where(ExamSchedule.school_id == school_id).order_by(ExamSchedule.exam_date, ExamSchedule.start_time)
        )
        schedules = rows.scalars().all()

        hall_map: dict[tuple[str, str, str], list[ExamSchedule]] = defaultdict(list)
        section_map: dict[tuple[str, str, str], list[ExamSchedule]] = defaultdict(list)
        clashes: list[dict[str, Any]] = []

        for exam in schedules:
            day_key = exam.exam_date.date().isoformat()
            start = exam.start_time.strftime("%H:%M")
            end = exam.end_time.strftime("%H:%M")
            hall_map[(day_key, start, exam.hall_name)].append(exam)
            section_map[(day_key, start, exam.section)].append(exam)
            if exam.registered_students > exam.hall_capacity:
                clashes.append(
                    {
                        "type": "capacity_overflow",
                        "exam_id": exam.id,
                        "exam_name": exam.exam_name,
                        "hall": exam.hall_name,
                        "registered": exam.registered_students,
                        "capacity": exam.hall_capacity,
                        "severity": "critical",
                    }
                )

        for key, grouped in hall_map.items():
            if len(grouped) > 1:
                clashes.append(
                    {
                        "type": "hall_double_booking",
                        "day": key[0],
                        "start": key[1],
                        "hall": key[2],
                        "exam_ids": [g.id for g in grouped],
                        "severity": "critical",
                    }
                )

        for key, grouped in section_map.items():
            if len(grouped) > 1:
                clashes.append(
                    {
                        "type": "section_double_booking",
                        "day": key[0],
                        "start": key[1],
                        "section": key[2],
                        "exam_ids": [g.id for g in grouped],
                        "severity": "critical",
                    }
                )

        reflection = f"Exam clash audit complete for {school_id}: {len(clashes)} clash records detected."
        return reflection, [
            {"status": "exam_schedule_loaded", "records": len(schedules)},
            {"status": "exam_clash_report", "clashes": clashes, "clash_count": len(clashes)},
        ]

    async def optimize_exam_schedule(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        rows = await db.execute(
            select(ExamSchedule)
            .where(ExamSchedule.school_id == school_id)
            .order_by(ExamSchedule.exam_date, ExamSchedule.start_time)
            .limit(100)
        )
        schedules = rows.scalars().all()

        by_day_section: dict[tuple[str, str], list[ExamSchedule]] = defaultdict(list)
        for exam in schedules:
            by_day_section[(exam.exam_date.date().isoformat(), exam.section)].append(exam)

        adjustments: list[dict[str, Any]] = []
        for (_day, _section), exams in by_day_section.items():
            if len(exams) <= 1:
                continue
            for idx, exam in enumerate(sorted(exams, key=lambda x: x.start_time)):
                if idx == 0:
                    continue
                old_day = exam.exam_date.date().isoformat()
                exam.exam_date = exam.exam_date + timedelta(days=idx)
                exam.start_time = exam.start_time + timedelta(days=idx)
                exam.end_time = exam.end_time + timedelta(days=idx)
                exam.status = ExamScheduleStatus.RESCHEDULED
                adjustments.append(
                    {
                        "exam_id": exam.id,
                        "exam_name": exam.exam_name,
                        "old_day": old_day,
                        "new_day": exam.exam_date.date().isoformat(),
                        "reason": "Reduced same-day section load",
                    }
                )

        for exam in schedules:
            if exam.registered_students <= exam.hall_capacity:
                continue
            original = exam.hall_name
            exam.hall_name = "Grand Hall"
            exam.hall_capacity = max(exam.registered_students + 10, 150)
            adjustments.append(
                {
                    "exam_id": exam.id,
                    "exam_name": exam.exam_name,
                    "old_hall": original,
                    "new_hall": exam.hall_name,
                    "reason": "Capacity overflow remediation",
                }
            )

        await db.flush()
        reflection = f"Optimized exam schedule for {school_id} with {len(adjustments)} adjustments."
        return reflection, [
            {"status": "optimization_inputs_loaded", "record_count": len(schedules)},
            {"status": "exam_optimization_completed", "adjustments": adjustments},
        ]

    async def generate_calendar(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_calendar_seed(db, school_id)

        start_raw = str(context.get("start_date") or "").strip()
        end_raw = str(context.get("end_date") or "").strip()
        today = datetime.now(timezone.utc)
        start = datetime.fromisoformat(start_raw).replace(tzinfo=timezone.utc) if start_raw else today.replace(month=7, day=1, hour=9, minute=0, second=0, microsecond=0)
        end = datetime.fromisoformat(end_raw).replace(tzinfo=timezone.utc) if end_raw else start + timedelta(days=150)

        holidays = self._as_list(context.get("holidays"))
        holiday_dates = set()
        for holiday in holidays:
            if isinstance(holiday, dict) and holiday.get("date"):
                holiday_dates.add(str(holiday["date"]))
            elif isinstance(holiday, str) and holiday:
                holiday_dates.add(holiday[:10])

        teaching_blocks = 0
        cursor = start
        generated: list[dict[str, Any]] = []
        while cursor <= end:
            if cursor.weekday() < 5:
                title = f"Teaching Day {cursor.strftime('%Y-%m-%d')}"
                event_type = CalendarEventType.TEACHING_DAY
                is_holiday = cursor.date().isoformat() in holiday_dates
                if is_holiday:
                    title = f"Holiday: {cursor.strftime('%Y-%m-%d')}"
                    event_type = CalendarEventType.HOLIDAY
                db.add(
                    AcademicCalendarEvent(
                        school_id=school_id,
                        title=title,
                        event_type=event_type,
                        start_at=cursor,
                        end_at=cursor + timedelta(hours=8),
                        owner="Academic Cell",
                        is_holiday=is_holiday,
                        is_locked=is_holiday,
                        metadata_json={"generated": True},
                    )
                )
                teaching_blocks += 0 if is_holiday else 1
                if len(generated) < 20:
                    generated.append({"date": cursor.date().isoformat(), "title": title, "event_type": event_type.value})
            cursor += timedelta(days=1)

        await db.flush()
        reflection = f"Generated calendar scaffold for {school_id} with {teaching_blocks} teaching days."
        return reflection, [
            {"status": "calendar_inputs_resolved", "start_date": start.date().isoformat(), "end_date": end.date().isoformat()},
            {"status": "calendar_generated", "teaching_days": teaching_blocks, "sample_events": generated},
        ]

    async def add_calendar_event(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        event = context.get("event") if isinstance(context.get("event"), dict) else {}

        title = str(event.get("name") or context.get("event_name") or "New Academic Event").strip()
        event_type_raw = str(event.get("type") or context.get("event_type") or "event").strip().lower()
        start_raw = str(event.get("date") or context.get("date") or datetime.now(timezone.utc).date().isoformat())

        start = datetime.fromisoformat(start_raw).replace(tzinfo=timezone.utc)
        end = start + timedelta(hours=6)

        kind = CalendarEventType.EVENT
        if event_type_raw == "holiday":
            kind = CalendarEventType.HOLIDAY
        elif event_type_raw == "exam":
            kind = CalendarEventType.EXAM
        elif event_type_raw == "teaching_day":
            kind = CalendarEventType.TEACHING_DAY

        overlap_rows = await db.execute(
            select(AcademicCalendarEvent).where(
                AcademicCalendarEvent.school_id == school_id,
                AcademicCalendarEvent.start_at <= end,
                AcademicCalendarEvent.end_at >= start,
            )
        )
        overlaps = overlap_rows.scalars().all()

        item = AcademicCalendarEvent(
            school_id=school_id,
            title=title,
            event_type=kind,
            start_at=start,
            end_at=end,
            owner=str(context.get("owner") or "Academic Cell"),
            is_holiday=kind == CalendarEventType.HOLIDAY,
            is_locked=kind in {CalendarEventType.EXAM, CalendarEventType.HOLIDAY},
            metadata_json={"overlap_count": len(overlaps)},
        )
        db.add(item)
        await db.flush()

        reflection = f"Added calendar event '{title}' with {len(overlaps)} potential overlaps."
        return reflection, [
            {"status": "calendar_overlap_check", "overlap_count": len(overlaps), "overlap_ids": [o.id for o in overlaps[:10]]},
            {
                "status": "calendar_event_added",
                "event": {
                    "id": item.id,
                    "title": item.title,
                    "event_type": item.event_type.value,
                    "date": item.start_at.date().isoformat(),
                },
            },
        ]

    async def holiday_mapping(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_calendar_seed(db, school_id)

        rows = await db.execute(select(AcademicCalendarEvent).where(AcademicCalendarEvent.school_id == school_id))
        events = rows.scalars().all()

        holidays = [e for e in events if e.event_type == CalendarEventType.HOLIDAY or e.is_holiday]
        teaching = [e for e in events if e.event_type == CalendarEventType.TEACHING_DAY and not e.is_holiday]
        lost_days = len([h for h in holidays if h.start_at.weekday() < 5])
        effective_days = max(0, len(teaching) - lost_days)
        recommendations = []
        if lost_days > 8:
            recommendations.append("Add 2 compensatory Saturdays for each programme cluster.")
        if effective_days < 90:
            recommendations.append("Shift one assessment week to blended mode to recover teaching hours.")
        if not recommendations:
            recommendations.append("Current holiday distribution is within academic tolerance bands.")

        reflection = (
            f"Holiday mapping complete for {school_id}: {lost_days} weekday holidays, "
            f"{effective_days} effective teaching days."
        )
        return reflection, [
            {
                "status": "holiday_inventory_built",
                "holiday_count": len(holidays),
                "weekday_holiday_count": lost_days,
                "teaching_day_count": len(teaching),
            },
            {
                "status": "holiday_impact_assessed",
                "effective_teaching_days": effective_days,
                "recommendations": recommendations,
            },
        ]

    async def export_calendar(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        rows = await db.execute(
            select(AcademicCalendarEvent)
            .where(AcademicCalendarEvent.school_id == school_id)
            .order_by(AcademicCalendarEvent.start_at.asc())
        )
        events = rows.scalars().all()

        month_buckets: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for event in events:
            month_key = event.start_at.strftime("%Y-%m")
            month_buckets[month_key].append(
                {
                    "id": event.id,
                    "date": event.start_at.date().isoformat(),
                    "title": event.title,
                    "type": event.event_type.value,
                    "owner": event.owner,
                }
            )

        export_rows = [{"month": month, "events": items} for month, items in sorted(month_buckets.items())]
        reflection = f"Prepared export payload for {school_id} calendar across {len(export_rows)} months."
        return reflection, [
            {"status": "calendar_rows_loaded", "event_count": len(events)},
            {"status": "calendar_export_ready", "month_wise_calendar": export_rows},
        ]

    async def audit_syllabus(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        await self.ensure_curriculum_seed(db, school_id)

        programme_filter = str(context.get("programme") or "").strip().lower()
        rows = await db.execute(select(CurriculumAuditEntry).where(CurriculumAuditEntry.school_id == school_id))
        audits = rows.scalars().all()

        if programme_filter:
            audits = [a for a in audits if programme_filter in a.programme.lower()]

        updated: list[dict[str, Any]] = []
        for audit in audits:
            gap = abs(audit.exam_frequency - audit.syllabus_weight)
            audit.alignment_score = round(max(35.0, min(98.0, (audit.industry_relevance + (100 - gap)) / 2)), 1)
            if audit.alignment_score >= 85:
                audit.status = CurriculumAuditStatus.ALIGNED
            elif audit.alignment_score >= 70:
                audit.status = CurriculumAuditStatus.REVIEWING
            else:
                audit.status = CurriculumAuditStatus.NEEDS_UPDATE

            gaps = []
            if gap > 25:
                gaps.append("Exam weight and syllabus weight are materially misaligned")
            if audit.industry_relevance < 65:
                gaps.append("Industry relevance is below target")
            if not gaps:
                gaps.append("No critical gaps detected")

            recommendations = [
                "Increase practical lab coverage for high-weight topics" if audit.industry_relevance < 75 else "Maintain current lab depth",
                "Revise assessment blueprint to match current syllabus weights",
            ]

            audit.gaps = gaps
            audit.recommendations = recommendations
            audit.last_audited_at = datetime.now(timezone.utc)
            updated.append(
                {
                    "course_code": audit.course_code,
                    "course_name": audit.course_name,
                    "alignment_score": audit.alignment_score,
                    "status": audit.status.value,
                    "gaps": gaps,
                }
            )

        await db.flush()
        reflection = f"Completed syllabus audit for {len(updated)} curriculum entries in {school_id}."
        return reflection, [
            {"status": "curriculum_scope_resolved", "entry_count": len(audits), "programme_filter": programme_filter or "all"},
            {"status": "syllabus_audit_completed", "updated_entries": updated[:25]},
        ]

    async def nep_compliance(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        rows = await db.execute(select(CurriculumAuditEntry).where(CurriculumAuditEntry.school_id == school_id))
        audits = rows.scalars().all()

        total = max(1, len(audits))
        aligned = len([a for a in audits if a.alignment_score >= 80])
        multidisciplinary_readiness = round((aligned / total) * 100, 1)
        abc_readiness = round(sum(min(100.0, a.industry_relevance + 5.0) for a in audits) / total, 1)
        obe_documentation = round(sum(max(0.0, 100.0 - abs(a.exam_frequency - a.syllabus_weight)) for a in audits) / total, 1)

        score = round((multidisciplinary_readiness + abc_readiness + obe_documentation) / 3, 1)
        status = "compliant" if score >= 75 else "partial_compliance"

        reflection = f"NEP compliance assessment complete for {school_id} with score {score}."
        return reflection, [
            {
                "status": "nep_compliance_assessed",
                "overall_score": score,
                "status_label": status,
                "metrics": {
                    "multidisciplinary_readiness": multidisciplinary_readiness,
                    "academic_bank_readiness": abc_readiness,
                    "obe_documentation": obe_documentation,
                },
            }
        ]

    async def industry_alignment(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        rows = await db.execute(select(CurriculumAuditEntry).where(CurriculumAuditEntry.school_id == school_id))
        audits = rows.scalars().all()

        sorted_low = sorted(audits, key=lambda x: float(x.industry_relevance))
        recommendations = [
            {
                "course_code": item.course_code,
                "course_name": item.course_name,
                "industry_relevance": item.industry_relevance,
                "recommendation": "Add project-based module on current industry tools" if item.industry_relevance < 70 else "Maintain and refresh case studies quarterly",
            }
            for item in sorted_low[:8]
        ]

        mean_score = round(sum(item.industry_relevance for item in audits) / max(1, len(audits)), 1)
        reflection = f"Industry alignment analysis complete for {school_id}, average relevance {mean_score}."
        return reflection, [
            {"status": "industry_benchmark_loaded", "entry_count": len(audits), "avg_industry_relevance": mean_score},
            {"status": "industry_alignment_report", "recommendations": recommendations},
        ]

    async def generate_curriculum_report(self, db: AsyncSession, context: dict[str, Any]) -> tuple[str, list[dict[str, Any]]]:
        school_id = self._school(context)
        rows = await db.execute(select(CurriculumAuditEntry).where(CurriculumAuditEntry.school_id == school_id))
        audits = rows.scalars().all()

        by_programme: dict[str, list[CurriculumAuditEntry]] = defaultdict(list)
        for audit in audits:
            by_programme[audit.programme].append(audit)

        report_rows: list[dict[str, Any]] = []
        for programme, items in sorted(by_programme.items()):
            avg_alignment = round(sum(item.alignment_score for item in items) / max(1, len(items)), 1)
            needs_update = len([item for item in items if item.status in {CurriculumAuditStatus.NEEDS_UPDATE, CurriculumAuditStatus.NON_COMPLIANT}])
            report_rows.append(
                {
                    "programme": programme,
                    "entry_count": len(items),
                    "avg_alignment": avg_alignment,
                    "needs_update": needs_update,
                }
            )

        low_courses = sorted(audits, key=lambda x: float(x.alignment_score))[:5]
        top_gaps = [
            {
                "course_code": item.course_code,
                "course_name": item.course_name,
                "alignment_score": item.alignment_score,
                "gaps": item.gaps,
            }
            for item in low_courses
        ]

        reflection = f"Generated curriculum audit report for {school_id} with {len(report_rows)} programme summaries."
        return reflection, [
            {"status": "programme_rollup_created", "programme_summaries": report_rows},
            {"status": "annual_audit_report_ready", "top_gap_courses": top_gaps},
        ]

    async def run_automation_cycle(self, db: AsyncSession, school_id: str, trigger_type: str, trigger_ref: str | None = None) -> dict[str, Any]:
        _, timetable_steps = await self.detect_timetable_conflicts(db, {"school_id": school_id})
        _, exam_steps = await self.check_exam_clashes(db, {"school_id": school_id})
        _, holiday_steps = await self.holiday_mapping(db, {"school_id": school_id})
        _, report_steps = await self.generate_curriculum_report(db, {"school_id": school_id})

        execution = [
            {"status": "timetable_guardrail", "detail": timetable_steps[-1] if timetable_steps else {}},
            {"status": "exam_guardrail", "detail": exam_steps[-1] if exam_steps else {}},
            {"status": "calendar_guardrail", "detail": holiday_steps[-1] if holiday_steps else {}},
            {"status": "curriculum_guardrail", "detail": report_steps[-1] if report_steps else {}},
        ]
        summary = (
            f"Automation cycle completed for {school_id}: "
            f"{execution[0]['status']}, {execution[1]['status']}, {execution[2]['status']}, {execution[3]['status']}."
        )

        run = AcademicsAutomationRun(
            school_id=school_id,
            trigger_type=trigger_type,
            trigger_ref=trigger_ref,
            status="success",
            summary=summary,
            execution_details=execution,
        )
        db.add(run)
        await db.flush()

        return {
            "run_id": run.id,
            "school_id": run.school_id,
            "trigger_type": run.trigger_type,
            "status": run.status,
            "summary": run.summary,
            "execution_details": run.execution_details,
            "created_at": run.created_at.isoformat() if run.created_at else datetime.now(timezone.utc).isoformat(),
        }


academics_ops_service = AcademicsOpsService()
